theme: jekyll-theme-cayman
title: HotaVN: Hợp tác kinh doanh
encoding: UTF-8
description: Hợp tác với HotaVN website học mọi thứ miễn phí
github:
 zip_url: https://hotavn.com/
 another_url: Go to HotaVN
